title: profil1
description: Portfolio Website
theme: jekyll-theme-primer
destination: public
source: public
sass:
  sass_dir: public/css  # Adjust path if your SCSS file is in a subfolder within public/css
